"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['intro_2.py']
DATA_FILES = ['/Users/alim/GitHub/DonorUniverseGit/images', '/Users/alim/GitHub/DonorUniverseGit/src/credentials.json']
OPTIONS = {'argv_emulation': False,'iconfile': '/Users/alim/Downloads/DonorUniverseLogo.png.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
